version = 1

exclude_patterns = [
    "lib/**",
    "css/**",
    "img/**",
    "public/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  runtime_env = [
    "browser",
    "node"
  ]